[package]
#this exists to access libjava dependencies.
name = "jvm"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-jvm-common = {path = "../rust-jvm-common"}
slow-interpreter = {path = "../slow-interpreter"}
jvmti-jni-bindings = {path = "../jvmti-jni-bindings"}
classfile-parser = {path = "../classfile-parser"}
classfile-view = {path = "../classfile-view"}
descriptor-parser = {path = "../descriptor-parser"}
libjvm-utils = {path = "../libjvm-utils"}
libc = "0.2.66"
num_cpus = "1.0"
regex = "1"
log = "0.4"
lock_api = "0.3.4"
parking_lot = "0.10.2"
simple_logger = "1.3.0"
nix = "0.17.0"