[package]
#this exists to access libjava dependencies.
name = "jvm"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-jni = {path = "../rust-jni"}
runtime-common = {path = "../runtime-common"}
rust-jvm-common = {path = "../rust-jvm-common"}
slow-interpreter = {path = "../slow-interpreter"}
[build-dependencies]
bindgen = "0.52.0"