[package]
name = "rust-jvm"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]


[lib]
name = "classfile"
path = "src/lib.rs"

#edition = "2018"
[dependencies]
argparse = "0.2.2"
num = "0.2.0"
bimap = "0.4"
log = "0.4"
simple_logger = "1.3.0"
tempfile = "3.1.0"
regex = "1.3.1"
walkdir = "2.2.9"
pathdiff = "0.1.0"
tokio = "0.1.22"
