[package]
name = "rust-jvm"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]

[[bin]]
name = "java"
path = "src/main.rs"

[dependencies]
rust-jvm-common = {path = "./rust-jvm-common"}
classfile-parser = {path = "./classfile-parser"}
verification = {path = "./verification"}
loading = {path = "./loading"}
slow-interpreter = {path = "./slow-interpreter"}
jar-manipulation = {path = "./jar-manipulation"}
rust-jni = {path = "./rust-jni"}
runtime-common = {path = "./runtime-common"}
argparse = "0.2.2"
log = "0.4"
simple_logger = "1.3.0"
walkdir = "2.2.9"
pathdiff = "0.1.0"



[workspace]
members = ["rust-jvm-common","classfile-parser", "verification", "slow-interpreter","loading","jar-manipulation","rust-jni", "runtime-common"]