[package]
name = "rust-jvm"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]

[[bin]]
name = "java"
path = "src/main.rs"

[dependencies]
rust-jvm-common = {path = "./rust-jvm-common"}
classfile-parser = {path = "./classfile-parser"}
verification = {path = "./verification"}
slow-interpreter = {path = "./slow-interpreter"}
jar-manipulation = {path = "./jar-manipulation"}
jni-bindings = {path = "./jni-bindings"}
jvm = {path = "./libjvm"}
classfile-view = {path = "./classfile-view"}
descriptor-parser = {path = "./descriptor-parser"}
jvmti-bindings = {path = "./jvmti-bindings"}
jvmti = {path = "./jvmti"}
argparse = "0.2.2"
log = "0.4"
simple_logger = "1.3.0"


[workspace]
members = ["rust-jvm-common",
           "classfile-parser",
           "verification",
           "slow-interpreter",
           "jar-manipulation",
           "libjvm",
           "jni-bindings",
           "libjvm-utils",
           "descriptor-parser",
           "classfile-view",
           "jvmti",
           "jvmti-bindings"]
