[package]
name = "rust-jvm"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"
[[bin]]
name = "java"
path = "src/main.rs"

[dependencies]
rust-jvm-common = {path = "./rust-jvm-common"}
classfile-parser = {path = "./classfile-parser"}
verification = {path = "./verification"}
slow-interpreter = {path = "./slow-interpreter"}
jar-manipulation = {path = "./jar-manipulation"}
jvm = {path = "./libjvm"}
classfile-view = {path = "./classfile-view"}
descriptor-parser = {path = "./descriptor-parser"}
jvmti-jni-bindings = {path = "./jvmti-jni-bindings"}
type-safe-proc-macro-utils = {path = "./type-safe-proc-macro-utils"}
argparse = "0.2.2"

[workspace]
members = ["rust-jvm-common",
           "classfile-parser",
           "verification",
           "slow-interpreter",
           "jar-manipulation",
           "libjvm",
           "descriptor-parser",
           "classfile-view",
           "jvmti-jni-bindings",
           "userspace-threads",
           "type-safe-proc-macro-utils"
           ]
