[package]
name = "verification"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
log = "0.4"
simple_logger = "1.3.0"
regex = "1.3.1"
rust-jvm-common = {path = "../rust-jvm-common"}
classfile-parser = {path = "../classfile-parser"}

[dev-dependencies]
ntest_timeout = "0.3.0"
timebomb = "0.1.2"
loading = {path = "../loading"}
jar-manipulation = {path = "../jar-manipulation"}