[package]
name = "slow-interpreter"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
rust-jvm-common = { path = "../rust-jvm-common" }
classfile-parser = { path = "../classfile-parser" }
verification = { path = "../verification" }
classfile-view = { path = "../classfile-view" }
jar-manipulation = { path = "../jar-manipulation" }
jvmti-jni-bindings = { path = "../jvmti-jni-bindings" }
jit-common = { path = "../jit-common" }
gc-memory-layout-common = { path = "../gc-memory-layout-common" }
threads = { path = "../threads" }
type-safe-proc-macro-utils = { path = "../type-safe-proc-macro-utils" }
sketch-jvm-version-of-utf8 = { path = "../sketch-jvm-version-of-utf8" }
libffi = { git = 'https://github.com/pirocks/libffi-rs.git' }
libloading = { git = 'https://github.com/pirocks/rust_libloading.git' }
libc = "0.2.66"
regex = "1"
va_list = "0.1.3"
lock_api = "0.3.4"
parking_lot = "0.11.1"
futures-intrusive = "0.3.0"
thread-priority = "0.2.0"
nix = "0.17.0"
errno = "0.2.5"
num = "0.2.1"
by_address = "1.0.4"
bimap = "0.5.2"
itertools = "0.10.0"
closure = "0.3.0"
crossbeam = { git = "https://github.com/pirocks/crossbeam.git" }

[build-dependencies]
bindgen = "0.53.2"