[package]
name = "slow-interpreter"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"

[dependencies]
rust-jvm-common = {path = "../rust-jvm-common"}
classfile-parser = {path = "../classfile-parser"}
verification = {path = "../verification"}
runtime-common = {path = "../runtime-common"}
#rust-jni = {path = "src/rust-jni"}
libloading = "0.5"
memalloc = "0.1"
log = "0.4"
simple_logger = "1.3.0"
jni = "0.14.0"
libc = "0.2.66"
libffi = "0.9.0"

[build-dependencies]
bindgen = "0.52.0"