[package]
name = "slow-interpreter"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
rust-jvm-common = {path = "../rust-jvm-common"}
classfile-parser = {path = "../classfile-parser"}
verification = {path = "../verification"}
classfile-view = {path = "../classfile-view"}
descriptor-parser = {path = "../descriptor-parser"}
jar-manipulation = {path = "../jar-manipulation"}
jvmti-jni-bindings = {path = "../jvmti-jni-bindings"}
libloading = "0.5"
log = "0.4"
simple_logger = "1.3.0"
libc = "0.2.66"
libffi = {git = 'https://github.com/pirocks/libffi-rs.git'}
regex = "1"
va_list = "0.1.3"
lock_api = "0.3.4"
parking_lot = "0.10.2"
futures-intrusive = "0.3.0"
thread-priority = "0.2.0"
nix = "0.17.0"
errno = "0.2.5"
syscall = "0.2.1"
num = "0.2.1"

[build-dependencies]
bindgen = "0.53.2"