[package]
name = "vtable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-jvm-common = { path = "../rust-jvm-common" }
another-jit-vm = { path = "../another-jit-vm" }
another-jit-vm-ir = { path = "../another-jit-vm-ir" }
runtime-class-stuff = { path = "../runtime-class-stuff" }
memoffset = "0.6"

[dependencies.iced-x86]
version = "1.15"
features = ["code_asm"]