[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["fs", "sync", "io-std", "io-util"] }
futures = "0.3"
anyhow = "1"
xshell = "0.2"
serde = { version = "1", features = ["derive"] }
ron = "0.8"
regex = "1"
shell-words = "1"
memory-limited-executor = { path = "../memory-limited-executor" }
memory-amount = { path = "../memory-amount" }
openjdk-test-parser = { path = "../openjdk-test-parser" }
thiserror = { version = "1" }
async-trait = "0.1"
glob = "0.3"
rayon = "1.5"
itertools = "0.10"
sha256 = "1.1"
wait-timeout = "0.2"