[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["fs"] }
anyhow = "1"
xshell = "0.2"
serde = "1"
ron = "0.8.0"
fs_extra = "1.2.0"
regex = "1.6.0"