[package]
name = "jmm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jmm-bindings = { path = "../jmm-bindings" }

[lib]
crate-type = ["cdylib"]