extern crate bindgen;

use std::env;
use std::path::PathBuf;
use std::fs::create_dir;

fn path_join(one: &str, two: &str) ->String{
    let mut path = PathBuf::new();
    path.push(one);
    path.push(two);
    path.into_os_string().into_string().unwrap()
}

fn main() {
    let jvm_include_path = env!("JVM_H");
    let jvm_md_include_path = env!("JVM_MD_H");
    let jni_md_include_path = env!("JNI_MD_H");
    let jni_include_path = env!("JNI_H");
    // println!("cargo:rerun-if-changed={}", path_join(jvm_include_path,"/jvm.h"));
    // println!("cargo:rerun-if-changed={}", path_join(jvm_md_include_path,"/jvm_md.h"));
    // println!("cargo:rerun-if-changed={}", path_join(jni_include_path,"/jni.h"));
    // println!("cargo:rerun-if-changed={}", path_join(jni_md_include_path,"/jni_md.h"));
    // println!("cargo:rerun-if-changed=wrapper.h");
    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg(format!("-I/{}", jvm_include_path))
        .clang_arg(format!("-I/{}", jvm_md_include_path))
        .clang_arg(format!("-I/{}", jni_include_path))
        .clang_arg(format!("-I/{}", jni_md_include_path))
        .blacklist_function("JVM_GetInterfaceVersion")
        .blacklist_function("JVM_IHashCode")
        .blacklist_function("JVM_MonitorWait")
        .blacklist_function("JVM_MonitorNotify")
        .blacklist_function("JVM_MonitorNotifyAll")
        .blacklist_function("JVM_Clone")
        .blacklist_function("JVM_InternString")
        .blacklist_function("JVM_CurrentTimeMillis")
        .blacklist_function("JVM_NanoTime")
        .blacklist_function("JVM_ArrayCopy")
        .blacklist_function("JVM_InitProperties")
        .blacklist_function("JVM_OnExit")
        .blacklist_function("JVM_Exit")
        .blacklist_function("JVM_Halt")
        .blacklist_function("JVM_GC")
        .blacklist_function("JVM_MaxObjectInspectionAge")
        .blacklist_function("JVM_TraceInstructions")
        .blacklist_function("JVM_TraceMethodCalls")
        .blacklist_function("JVM_TotalMemory")
        .blacklist_function("JVM_FreeMemory")
        .blacklist_function("JVM_MaxMemory")
        .blacklist_function("JVM_ActiveProcessorCount")
        .blacklist_function("JVM_LoadLibrary")
        .blacklist_function("JVM_UnloadLibrary")
        .blacklist_function("JVM_FindLibraryEntry")
        .blacklist_function("JVM_IsSupportedJNIVersion")
        .blacklist_function("JVM_IsNaN")
        .blacklist_function("JVM_FillInStackTrace")
        .blacklist_function("JVM_GetStackTraceDepth")
        .blacklist_function("JVM_GetStackTraceElement")
        .blacklist_function("JVM_InitializeCompiler")
        .blacklist_function("JVM_IsSilentCompiler")
        .blacklist_function("JVM_CompileClass")
        .blacklist_function("JVM_CompileClasses")
        .blacklist_function("JVM_CompilerCommand")
        .blacklist_function("JVM_EnableCompiler")
        .blacklist_function("JVM_DisableCompiler")
        .blacklist_function("JVM_StartThread")
        .blacklist_function("JVM_StopThread")
        .blacklist_function("JVM_IsThreadAlive")
        .blacklist_function("JVM_SuspendThread")
        .blacklist_function("JVM_ResumeThread")
        .blacklist_function("JVM_SetThreadPriority")
        .blacklist_function("JVM_Yield")
        .blacklist_function("JVM_Sleep")
        .blacklist_function("JVM_CurrentThread")
        .blacklist_function("JVM_CountStackFrames")
        .blacklist_function("JVM_Interrupt")
        .blacklist_function("JVM_IsInterrupted")
        .blacklist_function("JVM_HoldsLock")
        .blacklist_function("JVM_DumpAllStacks")
        .blacklist_function("JVM_GetAllThreads")
        .blacklist_function("JVM_SetNativeThreadName")
        .blacklist_function("JVM_DumpThreads")
        .blacklist_function("JVM_CurrentLoadedClass")
        .blacklist_function("JVM_CurrentClassLoader")
        .blacklist_function("JVM_GetClassContext")
        .blacklist_function("JVM_ClassDepth")
        .blacklist_function("JVM_ClassLoaderDepth")
        .blacklist_function("JVM_GetSystemPackage")
        .blacklist_function("JVM_GetSystemPackages")
        .blacklist_function("JVM_AllocateNewObject")
        .blacklist_function("JVM_AllocateNewArray")
        .blacklist_function("JVM_LatestUserDefinedLoader")
        .blacklist_function("JVM_LoadClass0")
        .blacklist_function("JVM_GetArrayLength")
        .blacklist_function("JVM_GetArrayElement")
        .blacklist_function("JVM_GetPrimitiveArrayElement")
        .blacklist_function("JVM_SetArrayElement")
        .blacklist_function("JVM_SetPrimitiveArrayElement")
        .blacklist_function("JVM_NewArray")
        .blacklist_function("JVM_NewMultiArray")
        .blacklist_function("JVM_GetCallerClass")
        .blacklist_function("JVM_FindPrimitiveClass")
        .blacklist_function("JVM_ResolveClass")
        .blacklist_function("JVM_FindClassFromBootLoader")
        .blacklist_function("JVM_FindClassFromClassLoader")
        .blacklist_function("JVM_FindClassFromClass")
        .blacklist_function("JVM_FindLoadedClass")
        .blacklist_function("JVM_DefineClass")
        .blacklist_function("JVM_DefineClassWithSource")
        .blacklist_function("JVM_GetClassName")
        .blacklist_function("JVM_GetClassInterfaces")
        .blacklist_function("JVM_GetClassLoader")
        .blacklist_function("JVM_IsInterface")
        .blacklist_function("JVM_GetClassSigners")
        .blacklist_function("JVM_SetClassSigners")
        .blacklist_function("JVM_GetProtectionDomain")
        .blacklist_function("JVM_IsArrayClass")
        .blacklist_function("JVM_IsPrimitiveClass")
        .blacklist_function("JVM_GetComponentType")
        .blacklist_function("JVM_GetClassModifiers")
        .blacklist_function("JVM_GetDeclaredClasses")
        .blacklist_function("JVM_GetDeclaringClass")
        .blacklist_function("JVM_GetClassSignature")
        .blacklist_function("JVM_GetClassAnnotations")
        .blacklist_function("JVM_GetClassTypeAnnotations")
        .blacklist_function("JVM_GetFieldTypeAnnotations")
        .blacklist_function("JVM_GetMethodTypeAnnotations")
        .blacklist_function("JVM_GetClassDeclaredMethods")
        .blacklist_function("JVM_GetClassDeclaredFields")
        .blacklist_function("JVM_GetClassDeclaredConstructors")
        .blacklist_function("JVM_GetClassAccessFlags")
        .blacklist_function("JVM_InvokeMethod")
        .blacklist_function("JVM_NewInstanceFromConstructor")
        .blacklist_function("JVM_GetClassConstantPool")
        .blacklist_function("JVM_ConstantPoolGetSize")
        .blacklist_function("JVM_ConstantPoolGetClassAt")
        .blacklist_function("JVM_ConstantPoolGetClassAtIfLoaded")
        .blacklist_function("JVM_ConstantPoolGetMethodAt")
        .blacklist_function("JVM_ConstantPoolGetMethodAtIfLoaded")
        .blacklist_function("JVM_ConstantPoolGetFieldAt")
        .blacklist_function("JVM_ConstantPoolGetFieldAtIfLoaded")
        .blacklist_function("JVM_ConstantPoolGetMemberRefInfoAt")
        .blacklist_function("JVM_ConstantPoolGetIntAt")
        .blacklist_function("JVM_ConstantPoolGetLongAt")
        .blacklist_function("JVM_ConstantPoolGetFloatAt")
        .blacklist_function("JVM_ConstantPoolGetDoubleAt")
        .blacklist_function("JVM_ConstantPoolGetStringAt")
        .blacklist_function("JVM_ConstantPoolGetUTF8At")
        .blacklist_function("JVM_GetMethodParameters")
        .blacklist_function("JVM_DoPrivileged")
        .blacklist_function("JVM_GetInheritedAccessControlContext")
        .blacklist_function("JVM_GetStackAccessControlContext")
        .blacklist_function("JVM_RegisterSignal")
        .blacklist_function("JVM_RaiseSignal")
        .blacklist_function("JVM_FindSignal")
        .blacklist_function("JVM_DesiredAssertionStatus")
        .blacklist_function("JVM_AssertionStatusDirectives")
        .blacklist_function("JVM_SupportsCX8")
        .blacklist_function("JVM_DTraceGetVersion")
        .blacklist_function("JVM_DTraceActivate")
        .blacklist_function("JVM_DTraceIsProbeEnabled")
        .blacklist_function("JVM_DTraceDispose")
        .blacklist_function("JVM_DTraceIsSupported")
        .blacklist_function("JVM_GetClassNameUTF")
        .blacklist_function("JVM_GetClassCPTypes")
        .blacklist_function("JVM_GetClassCPEntriesCount")
        .blacklist_function("JVM_GetClassFieldsCount")
        .blacklist_function("JVM_GetClassMethodsCount")
        .blacklist_function("JVM_GetMethodIxExceptionIndexes")
        .blacklist_function("JVM_GetMethodIxExceptionsCount")
        .blacklist_function("JVM_GetMethodIxByteCode")
        .blacklist_function("JVM_GetMethodIxByteCodeLength")
        .blacklist_function("JVM_GetMethodIxExceptionTableEntry")
        .blacklist_function("JVM_GetMethodIxExceptionTableLength")
        .blacklist_function("JVM_GetFieldIxModifiers")
        .blacklist_function("JVM_GetMethodIxModifiers")
        .blacklist_function("JVM_GetMethodIxLocalsCount")
        .blacklist_function("JVM_GetMethodIxArgsSize")
        .blacklist_function("JVM_GetMethodIxMaxStack")
        .blacklist_function("JVM_IsConstructorIx")
        .blacklist_function("JVM_IsVMGeneratedMethodIx")
        .blacklist_function("JVM_GetMethodIxNameUTF")
        .blacklist_function("JVM_GetMethodIxSignatureUTF")
        .blacklist_function("JVM_GetCPFieldNameUTF")
        .blacklist_function("JVM_GetCPMethodNameUTF")
        .blacklist_function("JVM_GetCPMethodSignatureUTF")
        .blacklist_function("JVM_GetCPFieldSignatureUTF")
        .blacklist_function("JVM_GetCPClassNameUTF")
        .blacklist_function("JVM_GetCPFieldClassNameUTF")
        .blacklist_function("JVM_GetCPMethodClassNameUTF")
        .blacklist_function("JVM_GetCPFieldModifiers")
        .blacklist_function("JVM_GetCPMethodModifiers")
        .blacklist_function("JVM_ReleaseUTF")
        .blacklist_function("JVM_IsSameClassPackage")
        .blacklist_function("JVM_GetLastErrorString")
        .blacklist_function("JVM_NativePath")
        .blacklist_function("JVM_Open")
        .blacklist_function("JVM_Close")
        .blacklist_function("JVM_Read")
        .blacklist_function("JVM_Write")
        .blacklist_function("JVM_Available")
        .blacklist_function("JVM_Lseek")
        .blacklist_function("JVM_SetLength")
        .blacklist_function("JVM_Sync")
        .blacklist_function("JVM_InitializeSocketLibrary")
        .blacklist_function("JVM_Socket")
        .blacklist_function("JVM_SocketClose")
        .blacklist_function("JVM_SocketShutdown")
        .blacklist_function("JVM_Recv")
        .blacklist_function("JVM_Send")
        .blacklist_function("JVM_Timeout")
        .blacklist_function("JVM_Listen")
        .blacklist_function("JVM_Connect")
        .blacklist_function("JVM_Bind")
        .blacklist_function("JVM_Accept")
        .blacklist_function("JVM_RecvFrom")
        .blacklist_function("JVM_SendTo")
        .blacklist_function("JVM_SocketAvailable")
        .blacklist_function("JVM_GetSockName")
        .blacklist_function("JVM_GetSockOpt")
        .blacklist_function("JVM_SetSockOpt")
        .blacklist_function("JVM_GetHostName")
        .blacklist_function("JVM_RawMonitorCreate")
        .blacklist_function("JVM_RawMonitorDestroy")
        .blacklist_function("JVM_RawMonitorEnter")
        .blacklist_function("JVM_RawMonitorExit")
        .blacklist_function("JVM_GetManagement")
        .blacklist_function("JVM_InitAgentProperties")
        .blacklist_function("JVM_GetEnclosingMethodInfo")
        .blacklist_function("JVM_GetThreadStateValues")
        .blacklist_function("JVM_GetThreadStateNames")
        .blacklist_function("JVM_GetVersionInfo")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .derive_debug(true)
        .rustfmt_bindings(true)
        .generate()
        .expect("Unable to generate bindings");
    let out_path = PathBuf::from("gen/");
    if !out_path.clone().into_boxed_path().exists() {
        create_dir(out_path.clone().into_boxed_path()).unwrap();
    }
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}