[package]
name = "jni-bindings"
version = "0.1.0"
authors = ["Francis Nixon <fpn17@imperial.ac.uk>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
[build-dependencies]
bindgen = "0.52.0"