[package]
name = "threads"
version = "0.1.0"
authors = ["Francis Nixon <13nixonf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23"
libc = "0.2.66"
lock_api = "0.3.4"
parking_lot = "0.10.2"
crossbeam = { git = "https://github.com/pirocks/crossbeam.git" }
metered = "0.8.0"

[build-dependencies]
bindgen = "0.53.2"