use std::io;
use std::io::Write;

use rust_jvm_common::classfile::{Classfile, InstructionInfo};
use rust_jvm_common::classfile::instruction_info_nums::InstructionTypeNum;

pub struct WriterContext<'l, T: Write> {
    pub writer: &'l mut T,
}

pub fn write_classfile(_classfile: &Classfile, _writer: &mut dyn Write) -> io::Result<()> {
    // let _context = WriterContext { writer };
    todo!()
}

impl<T: Write> WriterContext<'_, T> {
    pub fn write_u8(&mut self, byte: u8) -> io::Result<()> {
        self.writer.write_all(&[byte])
    }

    pub fn write_classfile_impl(&mut self, _classfile: &Classfile) -> io::Result<()> {
        todo!()
    }


    pub fn write_instruction_info(&mut self, instruction_info: &InstructionInfo) -> io::Result<()> {
        match instruction_info {
            InstructionInfo::aaload => todo!(),
            InstructionInfo::aastore => todo!(),
            InstructionInfo::aconst_null => todo!(),
            InstructionInfo::aload(_) => todo!(),
            InstructionInfo::aload_0 => todo!(),
            InstructionInfo::aload_1 => todo!(),
            InstructionInfo::aload_2 => todo!(),
            InstructionInfo::aload_3 => todo!(),
            InstructionInfo::anewarray(_) => todo!(),
            InstructionInfo::areturn => todo!(),
            InstructionInfo::arraylength => todo!(),
            InstructionInfo::astore(_) => todo!(),
            InstructionInfo::astore_0 => todo!(),
            InstructionInfo::astore_1 => todo!(),
            InstructionInfo::astore_2 => todo!(),
            InstructionInfo::astore_3 => todo!(),
            InstructionInfo::athrow => todo!(),
            InstructionInfo::baload => todo!(),
            InstructionInfo::bastore => todo!(),
            InstructionInfo::bipush(_) => todo!(),
            InstructionInfo::caload => todo!(),
            InstructionInfo::castore => todo!(),
            InstructionInfo::checkcast(_) => todo!(),
            InstructionInfo::d2f => todo!(),
            InstructionInfo::d2i => todo!(),
            InstructionInfo::d2l => todo!(),
            InstructionInfo::dadd => todo!(),
            InstructionInfo::daload => todo!(),
            InstructionInfo::dastore => todo!(),
            InstructionInfo::dcmpg => todo!(),
            InstructionInfo::dcmpl => todo!(),
            InstructionInfo::dconst_0 => todo!(),
            InstructionInfo::dconst_1 => todo!(),
            InstructionInfo::ddiv => todo!(),
            InstructionInfo::dload(_) => todo!(),
            InstructionInfo::dload_0 => todo!(),
            InstructionInfo::dload_1 => todo!(),
            InstructionInfo::dload_2 => todo!(),
            InstructionInfo::dload_3 => todo!(),
            InstructionInfo::dmul => todo!(),
            InstructionInfo::dneg => todo!(),
            InstructionInfo::drem => todo!(),
            InstructionInfo::dreturn => todo!(),
            InstructionInfo::dstore(_) => todo!(),
            InstructionInfo::dstore_0 => todo!(),
            InstructionInfo::dstore_1 => todo!(),
            InstructionInfo::dstore_2 => todo!(),
            InstructionInfo::dstore_3 => todo!(),
            InstructionInfo::dsub => todo!(),
            InstructionInfo::dup => todo!(),
            InstructionInfo::dup_x1 => todo!(),
            InstructionInfo::dup_x2 => todo!(),
            InstructionInfo::dup2 => todo!(),
            InstructionInfo::dup2_x1 => todo!(),
            InstructionInfo::dup2_x2 => todo!(),
            InstructionInfo::f2d => todo!(),
            InstructionInfo::f2i => todo!(),
            InstructionInfo::f2l => todo!(),
            InstructionInfo::fadd => todo!(),
            InstructionInfo::faload => todo!(),
            InstructionInfo::fastore => todo!(),
            InstructionInfo::fcmpg => todo!(),
            InstructionInfo::fcmpl => todo!(),
            InstructionInfo::fconst_0 => todo!(),
            InstructionInfo::fconst_1 => todo!(),
            InstructionInfo::fconst_2 => todo!(),
            InstructionInfo::fdiv => todo!(),
            InstructionInfo::fload(_) => todo!(),
            InstructionInfo::fload_0 => todo!(),
            InstructionInfo::fload_1 => todo!(),
            InstructionInfo::fload_2 => todo!(),
            InstructionInfo::fload_3 => todo!(),
            InstructionInfo::fmul => todo!(),
            InstructionInfo::fneg => todo!(),
            InstructionInfo::frem => todo!(),
            InstructionInfo::freturn => todo!(),
            InstructionInfo::fstore(_) => todo!(),
            InstructionInfo::fstore_0 => todo!(),
            InstructionInfo::fstore_1 => todo!(),
            InstructionInfo::fstore_2 => todo!(),
            InstructionInfo::fstore_3 => todo!(),
            InstructionInfo::fsub => todo!(),
            InstructionInfo::getfield(_) => todo!(),
            InstructionInfo::getstatic(_) => todo!(),
            InstructionInfo::goto_(_) => todo!(),
            InstructionInfo::goto_w(_) => todo!(),
            InstructionInfo::i2b => todo!(),
            InstructionInfo::i2c => todo!(),
            InstructionInfo::i2d => todo!(),
            InstructionInfo::i2f => todo!(),
            InstructionInfo::i2l => todo!(),
            InstructionInfo::i2s => todo!(),
            InstructionInfo::iadd => todo!(),
            InstructionInfo::iaload => todo!(),
            InstructionInfo::iand => todo!(),
            InstructionInfo::iastore => todo!(),
            InstructionInfo::iconst_m1 => todo!(),
            InstructionInfo::iconst_0 => todo!(),
            InstructionInfo::iconst_1 => todo!(),
            InstructionInfo::iconst_2 => todo!(),
            InstructionInfo::iconst_3 => todo!(),
            InstructionInfo::iconst_4 => todo!(),
            InstructionInfo::iconst_5 => todo!(),
            InstructionInfo::idiv => todo!(),
            InstructionInfo::if_acmpeq(_) => todo!(),
            InstructionInfo::if_acmpne(_) => todo!(),
            InstructionInfo::if_icmpeq(_) => todo!(),
            InstructionInfo::if_icmpne(_) => todo!(),
            InstructionInfo::if_icmplt(_) => todo!(),
            InstructionInfo::if_icmpge(_) => todo!(),
            InstructionInfo::if_icmpgt(_) => todo!(),
            InstructionInfo::if_icmple(_) => todo!(),
            InstructionInfo::ifeq(_) => todo!(),
            InstructionInfo::ifne(_) => todo!(),
            InstructionInfo::iflt(_) => todo!(),
            InstructionInfo::ifge(_) => todo!(),
            InstructionInfo::ifgt(_) => todo!(),
            InstructionInfo::ifle(_) => todo!(),
            InstructionInfo::ifnonnull(_) => todo!(),
            InstructionInfo::ifnull(_) => todo!(),
            InstructionInfo::iinc(_) => todo!(),
            InstructionInfo::iload(_) => todo!(),
            InstructionInfo::iload_0 => todo!(),
            InstructionInfo::iload_1 => todo!(),
            InstructionInfo::iload_2 => todo!(),
            InstructionInfo::iload_3 => todo!(),
            InstructionInfo::imul => todo!(),
            InstructionInfo::ineg => todo!(),
            InstructionInfo::instanceof(_) => todo!(),
            InstructionInfo::invokedynamic(_) => todo!(),
            InstructionInfo::invokeinterface(_) => todo!(),
            InstructionInfo::invokespecial(_) => todo!(),
            InstructionInfo::invokestatic(_) => todo!(),
            InstructionInfo::invokevirtual(_) => todo!(),
            InstructionInfo::ior => todo!(),
            InstructionInfo::irem => todo!(),
            InstructionInfo::ireturn => todo!(),
            InstructionInfo::ishl => todo!(),
            InstructionInfo::ishr => todo!(),
            InstructionInfo::istore(_) => todo!(),
            InstructionInfo::istore_0 => todo!(),
            InstructionInfo::istore_1 => todo!(),
            InstructionInfo::istore_2 => todo!(),
            InstructionInfo::istore_3 => todo!(),
            InstructionInfo::isub => todo!(),
            InstructionInfo::iushr => todo!(),
            InstructionInfo::ixor => todo!(),
            InstructionInfo::jsr(_) => todo!(),
            InstructionInfo::jsr_w(_) => todo!(),
            InstructionInfo::l2d => todo!(),
            InstructionInfo::l2f => todo!(),
            InstructionInfo::l2i => todo!(),
            InstructionInfo::ladd => todo!(),
            InstructionInfo::laload => todo!(),
            InstructionInfo::land => todo!(),
            InstructionInfo::lastore => todo!(),
            InstructionInfo::lcmp => todo!(),
            InstructionInfo::lconst_0 => todo!(),
            InstructionInfo::lconst_1 => todo!(),
            InstructionInfo::ldc(_) => todo!(),
            InstructionInfo::ldc_w(_) => todo!(),
            InstructionInfo::ldc2_w(_) => todo!(),
            InstructionInfo::ldiv => todo!(),
            InstructionInfo::lload(_) => todo!(),
            InstructionInfo::lload_0 => todo!(),
            InstructionInfo::lload_1 => todo!(),
            InstructionInfo::lload_2 => todo!(),
            InstructionInfo::lload_3 => todo!(),
            InstructionInfo::lmul => todo!(),
            InstructionInfo::lneg => todo!(),
            InstructionInfo::lookupswitch(_) => todo!(),
            InstructionInfo::lor => todo!(),
            InstructionInfo::lrem => todo!(),
            InstructionInfo::lreturn => todo!(),
            InstructionInfo::lshl => todo!(),
            InstructionInfo::lshr => todo!(),
            InstructionInfo::lstore(_) => todo!(),
            InstructionInfo::lstore_0 => todo!(),
            InstructionInfo::lstore_1 => todo!(),
            InstructionInfo::lstore_2 => todo!(),
            InstructionInfo::lstore_3 => todo!(),
            InstructionInfo::lsub => todo!(),
            InstructionInfo::lushr => todo!(),
            InstructionInfo::lxor => todo!(),
            InstructionInfo::monitorenter => todo!(),
            InstructionInfo::monitorexit => todo!(),
            InstructionInfo::multianewarray(_) => todo!(),
            InstructionInfo::new(_) => todo!(),
            InstructionInfo::newarray(_) => todo!(),
            InstructionInfo::nop => todo!(),
            InstructionInfo::pop => todo!(),
            InstructionInfo::pop2 => todo!(),
            InstructionInfo::putfield(_) => todo!(),
            InstructionInfo::putstatic(_) => todo!(),
            InstructionInfo::ret(_) => todo!(),
            InstructionInfo::return_ => {
                self.write_u8(InstructionTypeNum::return_ as u8)
            }
            InstructionInfo::saload => todo!(),
            InstructionInfo::sastore => todo!(),
            InstructionInfo::sipush(_) => todo!(),
            InstructionInfo::swap => todo!(),
            InstructionInfo::tableswitch(_) => todo!(),
            InstructionInfo::wide(_) => todo!(),
            InstructionInfo::EndOfCode => todo!(),
        }
    }
}
