[package]
name = "interface-fast-instanceof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
class-ids = { path = "../class-ids" }
itertools = "0.10"